#!/usr/bin/env bash

# Author: diperblue
# Date: 29/10/2023
# Version: 1.0
# Description: A shell script program that can be used as a library for       \
# installing shell software.


#------------Variables-------------
helpM="""This program is a standard shell script installation program.

There are some specifics to using the program.
To use the program:
	-i or --install
		Using this you will proceed with the normal installation.
"""
#----------------------------------

#-------------Analysis-------------
[[ "$UID" -ne "0" ]] && { echo "You need root."; exit 1; }
[[ ! $(type -P curl) ]] && { echo "You need curl."; exit 1; }
#----------------------------------

#-----------Installing-------------
curl https://raw.githubusercontent.com/Diperblue/StudyMan/main/src/studyman > /usr/bin/studyman
echo -e "\033[46mDownloading is moving to /usr/bin/studyman\033[0;0m"
echo -e "\033[46mChecking... /usr/bin/studyman\033[0;0m"
if ! type -P studyman > /dev/null;then
	echo "\033[31mAn error has occurred!\033[0;0m"
	exit 1
fi
echo -e "The installation was successful!"
#----------------------------------